### ISSUE TITLE
[VIMEO] Unlisted Video is not loaded

### ISSUE THREAD

**Issue by qlaffont** [vidstack/player#1124] opened 2024-01-31 07:53 UTC
### Current Behavior:

Actually I want to load a unlisted video hosted in vimeo, but it doesn't work. Only If i publish the video in public.

### Expected Behavior:

Video should load

### Steps To Reproduce:

- use src as = `vimeo/907879935?hash=ecb2787474`

### Environment:

- Framework: Solid
- Meta Framework: Solid-Start
- Node: 18.18.2
- Device: Dell XPS
- OS: PopOS
- Browser: Chrome@121.0.6167.85 

### Anything Else?
Vimeo embed code : 
```
<div style=“padding:56.25% 0 0 0;position:relative;“><iframe src=“[https://player.vimeo.com/video/907879935?h=ecb2787474&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479](https://player.vimeo.com/video/907879935?h=ecb2787474&badge=0&autopause=0&player_id=0&app_id=58479)” frameborder=“0" allow=“autoplay; fullscreen; picture-in-picture” style=“position:absolute;top:0;left:0;width:100%;height:100%;” title=“1 Le téléphone reste un problème (patientèle ouverte)“></iframe></div><script src=”
https://player.vimeo.com/api/player.js”></script>
```

![annotely_image](https://github.com/vidstack/player/assets/10044790/266abccc-c684-4533-b148-d7f91b6394e7)
![image](https://github.com/vidstack/player/assets/10044790/d52ce115-8c56-425f-a06c-82f75e112b01)

**Comment by qlaffont** [comment] 2024-01-31 10:04
Discord issue closed as seen with @mihar-22

**Comment by mihar-22** [comment] 2024-01-31 10:18
Closing as it's a duplicate of https://github.com/vidstack/player/issues/1100

**Closed by mihar-22** 2024-01-31 10:18 UTC
Labels: bug

**Comment by imadys** [comment] 2024-05-10 12:55
Hello, 
What about URLs contains two IDs ?
`https://vimeo.com/${idOne}/${idTwo}`
