### ISSUE TITLE
Dash videos not autoplaying

### ISSUE THREAD

**Issue by ATypescriptEnjoyer** [vidstack/player#1345] opened 2024-07-11 13:47 UTC
### Current Behavior:

Videos via dash don't autoplay, and "auto" quality basically perma sets itself to 144p. Even if it remembers I want 1080p, upon manually clicking start it sets itself to low quality.

### Expected Behavior:

 Video autoplays with a good auto quality, it easily runs in max quality if i manually set it after starting the video.

### Steps To Reproduce:

    Enable dash
    Go to a video
    See in your console it shows a warning
    Manually click start

**Reproduction Link:** [How to create a repro?][repro]

https://www.vidstack.io/player/demo?framework=react&view=player

Swap the player to "Dash"

### Environment:

- Device: Fedora 40 Desktop
- Browser: Floorp@11.15.0
### Anything Else?

![image](https://github.com/vidstack/player/assets/8694395/83a5d50e-f7df-4685-9711-c1487574390b)

**Comment by mihar-22** [comment] 2024-07-24 00:55
I can't reproduce either issue, you'll need to provide a proper repro for me to debug any of these issues. Closing until one is provided.

Please see [Autoplay Policy](https://www.vidstack.io/docs/player/api/autoplay?styling=default-theme#autoplay-policy) to make sure autoplay is not failing due to the browser rejection. On a site a user does not regularly visit and play videos you'll need to mute the video.

**Closed by mihar-22** 2024-07-24 00:55 UTC
Labels: bug
