### ISSUE TITLE
'play' loading strategy fails on iOS Safari (v1.12.9)

### ISSUE THREAD

**Issue by wplit** [vidstack/player#1395] opened 2024-08-15 02:06 UTC
If we set 'play' as the loading strategy, when using the Youtube provider, pressing play on iOS loads the video but then doesn't allow play back.

Also, maybe related or a seperate issue - on desktop Safari, we also have an issue where pressing play needs to be done twice.

edit - it's not unique to Youtube, for Vimeo there's a similar issue with the play loading strategy, on iOS Safari it needs two clicks to play the video. The first click only loads the video but it doesn't actually play until we click again.

Not coming across the same issue with other providers, only when using Youtube & Vimeo.

(i believe it's a relatively new issue, it was working before but I don't recall which versions)

**Comment by Mat4m0** [comment] 2024-09-05 15:43
I have a similar issue in all Browsers (Firefox, Chrome, Safari), using HLS/Dash Provider with Cloudflare Video in a Nuxt Project.

Since the initial page load is pretty high when buffering almost the whole video get loaded, I wanted to use the load="play" property.

When clicking the play button, I get these errors:

<img width="768" alt="image" src="https://github.com/user-attachments/assets/8a4213dd-fabd-4dc4-b062-876ffeaa1102">

I have to click again so that the video get started,
Please let me know, if I should try to set up a reproduction.

**Comment by mihar-22** [comment] 2024-09-14 07:18
Unfortunately I can't repro either issue from my end using the YouTube provider on iOS Safar 17.6.1. I also can't repro the double play requreiment bug. Closing until we can repro.

**Closed by mihar-22** 2024-09-14 07:18 UTC
Labels: bug

**Comment by wplit** [comment] 2024-09-15 11:33
@mihar-22 

Hopefully this helps, 

View with iPhone - https://vidstack.baseui.co/

it's just default vidstack layout, added via web components with Youtube src. One with load=visible and one with load=play. The play one doesn't actually play the video when I try from iOS (same issue if I use vimeo source also, works fine for the others). 

(I'm unable to get the Youtube embed loading properly inside stackblitz,  jsfiddle, codepen etc so couldn't create a repro there)

**Comment by wplit** [comment] 2024-09-15 11:46
What we see from iOS.. the video loads but can't play and gets stuck

https://github.com/user-attachments/assets/ed3aa1d4-9158-49d8-99dc-f6adf7301e65

**Comment by mihar-22** [comment] 2024-09-15 11:49
Need more information. What version are you testing on? What iPhone model? Is it a simulator or real device?

**Comment by wplit** [comment] 2024-09-15 11:51
The latest version, the above demo is using the CDN - https://cdn.vidstack.io/player

I'm on a real device, iPhone SE2.

**Comment by wplit** [comment] 2024-09-16 00:02
@mihar-22 New info..

I've tested back to vidstack 1.12.8 and we see different behaviour with 1.12.8. On first click the video loads, and then on second click the video plays.

This was a previous bug that was fixed, changed in v1.12.9 - _"Youtube does not play on first request"_

Since 1.12.9, it behaves slightly differently. Now only needing one click to play. 

However, if the media player is set to 'load=play' and are on iPhone, the video then becomes unplayable (whereas previous you could play it, but it took two clicks). Now the first click loads the video and the media player instantly gets stuck. (it thinks it's playing, showing the pause icon etc, but the video isn't actually playing in the embed and can't be played no matter how many times it's clicked again)

Two demos showing the difference, from the two versions.. the first media player on each one is the 'play' loading strategy

Old version (v1.12.8) - where it takes two clicks but can be played - https://vidstack.baseui.co/1-12-8/
New version (v1.12.10) - can't be played on iphone no matter how many clicks - https://vidstack.baseui.co/

Let me know how to better provide a repro if the above isn't enough. If youtube embeds worked in stackblitz I could add it in there but it never works.

**Comment by wplit** [comment] 2024-10-04 01:41
My workaround, for anybody hitting this issue, is to change the loading strategy dynamically to 'custom' when on iOS detected, (and the provider is either YT or Vimeo), and then manually load the player on click with player.startLoading();

it means it takes two clicks to play the video, one to load the iframe, one to play the video. But it's a useful fallback.

**Comment by lexakami** [comment] 2025-03-18 21:11
This exact issue is happening for me too with the `play` load strategy with iOS not playing the video at all, and in desktop Safari 18.2 needing two clicks to play the video.

I've tried using a custom load strategy to load the video on click, and then `onCanPlay` to play the video using `useMediaRemote`, but that doesn't seem to work - it still tries to play before it's ready to be played.

**Comment by timoostrich** [comment] 2025-11-14 09:52
Same problem here on iOS / Safari and MacOS Safari. Using 

> load="play"

 is not working.
