### ISSUE TITLE
Import vidstack module problem

### ISSUE THREAD

**Issue by TomasRamosFerreira** [vidstack/player#628] opened 2022-03-12 20:35 UTC
When I import the dependencies of vidstack it gives me an error on import, however I install all dependencies and I can access the dependencies manualy.

It gives the following error:

![image](https://user-images.githubusercontent.com/64753278/158034035-2aefc66a-d1d9-487f-a8ee-e19f4d9544f9.png)

<details>
  <summary>Stack Traces</summary>

ERROR in ./src/pages/Scenarios/Scenario.jsx 58:41-46

export 'Video' (imported as 'Video') was not found in '@vidstack/player/react' (module has no exports)

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 2:0-63

Module not found: Error: Can't resolve './components/AspectRatio' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'AspectRatio.js'?
BREAKING CHANGE: The request './components/AspectRatio' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 3:0-57

Module not found: Error: Can't resolve './components/Audio' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'Audio.js'?
BREAKING CHANGE: The request './components/Audio' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 4:0-63

Module not found: Error: Can't resolve './components/AudioPlayer' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'AudioPlayer.js'?
BREAKING CHANGE: The request './components/AudioPlayer' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 5:0-68

Module not found: Error: Can't resolve './components/FullscreenButton' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'FullscreenButton.js'?
BREAKING CHANGE: The request './components/FullscreenButton' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 6:0-59

Module not found: Error: Can't resolve './components/Gesture' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'Gesture.js'?
BREAKING CHANGE: The request './components/Gesture' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 7:0-55

Module not found: Error: Can't resolve './components/Hls' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'Hls.js'?
BREAKING CHANGE: The request './components/Hls' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 8:0-61

Module not found: Error: Can't resolve './components/HlsPlayer' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'HlsPlayer.js'?
BREAKING CHANGE: The request './components/HlsPlayer' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 9:0-67

Module not found: Error: Can't resolve './components/MediaController' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'MediaController.js'?
BREAKING CHANGE: The request './components/MediaController' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 10:0-62

Module not found: Error: Can't resolve './components/MediaSync' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'MediaSync.js'?
BREAKING CHANGE: The request './components/MediaSync' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 11:0-60

Module not found: Error: Can't resolve './components/MediaUi' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'MediaUi.js'?
BREAKING CHANGE: The request './components/MediaUi' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 12:0-68

Module not found: Error: Can't resolve './components/MediaVisibility' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'MediaVisibility.js'?
BREAKING CHANGE: The request './components/MediaVisibility' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 13:0-63

Module not found: Error: Can't resolve './components/MuteButton' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'MuteButton.js'?
BREAKING CHANGE: The request './components/MuteButton' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 14:0-63

Module not found: Error: Can't resolve './components/PlayButton' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'PlayButton.js'?
BREAKING CHANGE: The request './components/PlayButton' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 15:0-59

Module not found: Error: Can't resolve './components/Poster' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'Poster.js'?
BREAKING CHANGE: The request './components/Poster' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 16:0-59

Module not found: Error: Can't resolve './components/Slider' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'Slider.js'?
BREAKING CHANGE: The request './components/Slider' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 17:0-68

Module not found: Error: Can't resolve './components/SliderValueText' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'SliderValueText.js'?
BREAKING CHANGE: The request './components/SliderValueText' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 18:0-64

Module not found: Error: Can't resolve './components/SliderVideo' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'SliderVideo.js'?
BREAKING CHANGE: The request './components/SliderVideo' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 19:0-57

Module not found: Error: Can't resolve './components/Time' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'Time.js'?
BREAKING CHANGE: The request './components/Time' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 20:0-63

Module not found: Error: Can't resolve './components/TimeSlider' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'TimeSlider.js'?
BREAKING CHANGE: The request './components/TimeSlider' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 21:0-65

Module not found: Error: Can't resolve './components/ToggleButton' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'ToggleButton.js'?
BREAKING CHANGE: The request './components/ToggleButton' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 22:0-58

Module not found: Error: Can't resolve './components/Video' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'Video.js'?
BREAKING CHANGE: The request './components/Video' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 23:0-64

Module not found: Error: Can't resolve './components/VideoPlayer' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'VideoPlayer.js'?
BREAKING CHANGE: The request './components/VideoPlayer' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@vidstack/player/dist/react/index.js 24:0-65

Module not found: Error: Can't resolve './components/VolumeSlider' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules\@vidstack\player\dist\react'
Did you mean 'VolumeSlider.js'?
BREAKING CHANGE: The request './components/VolumeSlider' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
</details>

**Comment by mihar-22** [comment] 2022-03-12 23:45
Hey @TomasRamosFerreira!

I just tested this with Vite and couldn't repro. I need more information on what bundler and environment (client/node) this issue is occuring in.

---

Quick tip, you can place long code snippets inside a collapsible section to make the issue easier to read like so:

```md
<details>
  <summary>Stack Traces</summary>
  
  Stack traces go here.
</details>
```

**Comment by TomasRamosFerreira** [comment] 2022-03-13 17:36
> 

Hi @mihar-22, thanks for your advice.
I'm using the following versions:
<details>
  <summary>Software versions</summary>

  1- node:  v16.13.2
  2- npm:  8.5.4
  3- yarn: 1.22.5
  4- react:  ^17.0.2
  5- webpack: ^5.70.0
</details>

The code that I used to test as that on the vidstack page for react. You can see it at the following url: https://www.vidstack.io/docs/player/getting-started/quickstart/react/video
<details>
  <summary>React code used</summary>

  import { Video } from '@vidstack/player/react';

  function Scenario() {
     return {
       <Video
	    src="https://media-files.vidstack.io/720p.mp4"
	    poster="https://media-files.vidstack.io/poster.png"
	    controls
	    loading="lazy"
        />
    }

  export default Scenario
</details>

And it gives me the following error:
<details>
  <summary>Error occurred</summary>
  
  ERROR in ./src/pages/Scenarios/Scenario.jsx 58:41-46

  export 'Video' (imported as 'Video') was not found in '@vidstack/player/react' (module has no exports)
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 2:0-63
  
  Module not found: Error: Can't resolve './components/AspectRatio' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'AspectRatio.js'?
  BREAKING CHANGE: The request './components/AspectRatio' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 3:0-57
  
  Module not found: Error: Can't resolve './components/Audio' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'Audio.js'?
  BREAKING CHANGE: The request './components/Audio' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 4:0-63
  
  Module not found: Error: Can't resolve './components/AudioPlayer' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'AudioPlayer.js'?
  BREAKING CHANGE: The request './components/AudioPlayer' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 5:0-68
  
  Module not found: Error: Can't resolve './components/FullscreenButton' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'FullscreenButton.js'?
  BREAKING CHANGE: The request './components/FullscreenButton' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 6:0-59
  
  Module not found: Error: Can't resolve './components/Gesture' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'Gesture.js'?
  BREAKING CHANGE: The request './components/Gesture' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 7:0-55
  
  Module not found: Error: Can't resolve './components/Hls' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'Hls.js'?
  BREAKING CHANGE: The request './components/Hls' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 8:0-61
  
  Module not found: Error: Can't resolve './components/HlsPlayer' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'HlsPlayer.js'?
  BREAKING CHANGE: The request './components/HlsPlayer' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 9:0-67
  
  Module not found: Error: Can't resolve './components/MediaController' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'MediaController.js'?
  BREAKING CHANGE: The request './components/MediaController' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 10:0-62
  
  Module not found: Error: Can't resolve './components/MediaSync' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'MediaSync.js'?
  BREAKING CHANGE: The request './components/MediaSync' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 11:0-60
  
  Module not found: Error: Can't resolve './components/MediaUi' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'MediaUi.js'?
  BREAKING CHANGE: The request './components/MediaUi' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 12:0-68
  
  Module not found: Error: Can't resolve './components/MediaVisibility' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'MediaVisibility.js'?
  BREAKING CHANGE: The request './components/MediaVisibility' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 13:0-63
  
  Module not found: Error: Can't resolve './components/MuteButton' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'MuteButton.js'?
  BREAKING CHANGE: The request './components/MuteButton' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 14:0-63
  
  Module not found: Error: Can't resolve './components/PlayButton' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'PlayButton.js'?
  BREAKING CHANGE: The request './components/PlayButton' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 15:0-59
  
  Module not found: Error: Can't resolve './components/Poster' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'Poster.js'?
  BREAKING CHANGE: The request './components/Poster' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 16:0-59
  
  Module not found: Error: Can't resolve './components/Slider' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'Slider.js'?
  BREAKING CHANGE: The request './components/Slider' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 17:0-68
  
  Module not found: Error: Can't resolve './components/SliderValueText' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'SliderValueText.js'?
  BREAKING CHANGE: The request './components/SliderValueText' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 18:0-64
  
  Module not found: Error: Can't resolve './components/SliderVideo' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'SliderVideo.js'?
  BREAKING CHANGE: The request './components/SliderVideo' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 19:0-57
  
  Module not found: Error: Can't resolve './components/Time' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'Time.js'?
  BREAKING CHANGE: The request './components/Time' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 20:0-63
  
  Module not found: Error: Can't resolve './components/TimeSlider' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'TimeSlider.js'?
  BREAKING CHANGE: The request './components/TimeSlider' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 21:0-65
  
  Module not found: Error: Can't resolve './components/ToggleButton' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'ToggleButton.js'?
  BREAKING CHANGE: The request './components/ToggleButton' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 22:0-58
  
  Module not found: Error: Can't resolve './components/Video' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'Video.js'?
  BREAKING CHANGE: The request './components/Video' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 23:0-64
  
  Module not found: Error: Can't resolve './components/VideoPlayer' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'VideoPlayer.js'?
  BREAKING CHANGE: The request './components/VideoPlayer' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
  
  ERROR in ./node_modules/@vidstack/player/dist/react/index.js 24:0-65
  
  Module not found: Error: Can't resolve './components/VolumeSlider' in 'C:\Users\Asus\Documents\GitHub\HackLab\front-end\node_modules@vidstack\player\dist\react'
  Did you mean 'VolumeSlider.js'?
  BREAKING CHANGE: The request './components/VolumeSlider' failed to resolve only because it was resolved as fully specified
  (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '.mjs' file, or a '.js' file where the package.json contains '"type": "module"').
  The extension in the request is mandatory for it to be fully specified.
  Add the extension to the request.
</details>

**Comment by Novezeil** [comment] 2022-03-15 19:01
turn off `fullySpecified` for `*.mjs` should do, according to https://github.com/webpack/webpack/issues/11467#issuecomment-691873586

```js
{
  test: /\.m?js/,
  type: "javascript/auto",
},
{
  test: /\.m?js/,
  resolve: {
    fullySpecified: false,
  },
},
```

**Comment by mihar-22** [comment] 2022-03-16 04:24
Duplicate of https://github.com/vidstack/player/issues/631.

**Closed by mihar-22** 2022-03-16 04:24 UTC
