### ISSUE TITLE
Having trouble integrating MediaPlayer into an NX Monorepo React project

### ISSUE THREAD

**Issue by balazs-karsai** [vidstack/player#1083] opened 2024-01-12 10:49 UTC
### Discussed in https://github.com/vidstack/player/discussions/1075

<div type='discussions-op-text'>

<sup>Originally posted by **balazs-karsai** January  8, 2024</sup>
I'm trying to replace Plyr with vidstack player on an NX Monorepo in a React app.
When I import and add MediaPlayer component, I get the following Typescript error:

`Type instantiation is excessively deep and possibly infinite`

I can dismiss the error with @ts-ignore, but I would like to solve it instead of just ignoring.
Also, while the app and video playing works, my Jest tests fail with the following error and it might be related to the issue above:

` ● Test suite failed to run
    Jest encountered an unexpected token
    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
    By default "node_modules" folder is ignored by transformers.
    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation
    Details:
    \node_modules\@vidstack\react\dist\prod\vidstack.js:3
    import { D as DOMEvent, f as isString, l as listenEvent, A as createReactComponent, u as useStateContext, B as useReactContext, a as useSignal, C as composeRefs, b as useSignalRecord, e as effect, E as useReactScope, s as signal, x as scoped } from './chunks/vidstack-8AXyyPGc.js';
    ^^^^^^
    SyntaxError: Cannot use import statement outside a module`

I tried to figure out the cause of the issue here but I couldn't find any solution. It seems like some Jest config issue, but I haven't changed anything, only added @vidstack-react as a dependency.

We are using
Node 18.19.0
Typescript 5.3.3
Jest 29.4.1
React 18.2.0
</div>

**Comment by mihar-22** [comment] 2024-01-14 03:50
Thanks for reporting. No need to cross-post in the future, either open an issue or a discussion but not both. In this case it seems to be an issue. If you can provide a repro so we can test the issue that would be great.

**Comment by mihar-22** [comment] 2024-01-16 02:03
Closing until a repro is provided.

**Comment by balazs-karsai** [comment] 2024-01-26 12:50
[videoplayer_bug.zip](https://github.com/vidstack/player/files/14064975/videoplayer_bug.zip)
Here I attached a sample package that reproduces the issue.

Please unpack the archive, than issue:
`yarn install`
`yarn test-all`

This should produce the above error. Also, in the Root.tsx file, there is a @ts-ignore annnotation to suppress another error: Type instantiation is excessively deep and possibly infinite. These two errors maybe related.

I used yarn 1.22.19 if that matters.

Please let me know if you need anything else.

**Comment by balazs-karsai** [comment] 2024-01-29 10:19
> Closing until a repro is provided.

Can I reopen the issue or create a new one?

**Comment by mihar-22** [comment] 2024-02-20 05:48
Unfortunately no luck reproducing this issue. I created a fresh NX monorepro project and found no issues. Try updating your package lock and version of TypeScript.

**Closed by mihar-22** 2024-02-20 05:48 UTC

**Comment by balazs-karsai** [comment] 2024-03-21 10:13
I still encounter the above error, even when updating to @vidstack/react 1.10.9
Have you run the tests for the example I provided? Because the code compiles, but tests fail with import errors in Vidstack.

**Comment by balazs-karsai** [comment] 2024-03-21 10:44
I also tried to add 
`transformIgnorePatterns: ['/node_modules/(?!@vidstack)'],`
into jest config, because it seems that some js files in Vidstack are not transpiled, but this config option only raised further errors.

**Comment by balazs-karsai** [comment] 2024-03-22 08:10
I think the main problem here is that Vidstack is using ESM modules that work fine with Vitest, but not with Jest. Do you know any way that we can use Vidstack without having to switch from Jest to Vitest?

**Comment by dandmcd** [comment] 2024-04-30 01:06
Has anyone found a way to get it to pass tests with Jest?  Anyone have a mock they can share?  I'd love to use Vitest, but that isn't an option at the moment as we were all in on Jest long before we looked at the Vidstack Player as a solution for video.

**Comment by JavierMartinz** [comment] 2025-02-18 09:48
As a last resort, if you're still getting the error, you can mock the @vidstack/react package entirely. In case you are using React and Plyr layout:

```js
jest.mock('@vidstack/react', () => ({
  MediaPlayer: jest.fn().mockImplementation(({ children }) => children),
  MediaProvider: jest.fn().mockImplementation(({ children }) => children),
}));

jest.mock('@vidstack/react/player/layouts/plyr', () => ({
  PlyrLayout: jest.fn().mockImplementation(({ children }) => children),
}));
```
