### ISSUE TITLE
After reaching the end of a clip and seeking backwards the `currentTime` does not get updated.

### ISSUE THREAD

**Issue by vorillaz** [vidstack/player#1348] opened 2024-07-12 12:37 UTC
### Current Behavior:

Using the subscriber and watching for changes on `currentTime` returrns the clip duration once the play ends and stops.

### Expected Behavior:

`currentTime` should get updated according to the player's state.

### Steps To Reproduce:

Example: steps to reproduce the behavior:
1. Start a video, wait for it to end.
2. Move the progress backwards.
3. `currentTime` is stuck to the end (duration) of the video.

Code used to watch for time changes
```
videoRef.current!.subscribe(({ currentTime, canPlay, seeking }) => {
  console.log("currenttime", currentTime);    
});
```

### Video with the bug

https://github.com/user-attachments/assets/fdd88f33-0aa6-418c-94ab-2fd423597795

### Environment:
- Framework: React

**Comment by mihar-22** [comment] 2024-07-20 05:57
Thanks for reporting! I can't reproduce the issue on my end, works as expected. I can debug this further if you can provide a reproduction. Closing until one is provided.

**Closed by mihar-22** 2024-07-20 05:57 UTC
Labels: bug

**Comment by ameytessact** [comment] 2024-09-27 06:41
https://www.vidstack.io/player/demo

I am able to see this issue in the demo. After the video finishes, try to seek backwards using pointer or arrow keys and then play the video. The video plays from the beginning instead of the seeked time.

**Comment by s-shin** [comment] 2025-02-16 20:56
> https://www.vidstack.io/player/demo
> 
> I am able to see this issue in the demo. After the video finishes, try to seek backwards using pointer or arrow keys and then play the video. The video plays from the beginning instead of the seeked time.

It looks like a bug to me too. Can this issue be reopened?

**Comment by jozsefDevs** [comment] 2025-02-24 10:29
I think this is an issue too. Also additionally, when you reached end of video and try to call `seek(X) and play()` again, the video will just start to play from beginning, and doesn't mind the `seek` call et all.  If you do these calls while video is anywhere playback but the end, it works well.

**Comment by ZoltanDalmadi** [comment] 2025-03-17 11:30
@mihar-22 any hope of this getting fixed? It is clearly reproducible in the demo as others mentioned.

**Comment by chrisspiegl** [comment] 2025-08-03 12:05
I am running into the same issue as it is reported here. It feels like something that many people have experienced and would like fixed.

For me the expected behavior would be:

- Video Ends => show "replay button" => start from beginning
- User starts seeking in any way (pointer, keyboard, etc.) => "replay button" goes back to "play/pause" button => play from where the user has seeked to

**Comment by ameytessact** [comment] 2025-08-04 06:27
I had to add this custom code to prevent the video from restarting after `ended` was emitted.
https://github.com/vidstack/player/issues/1531#issuecomment-3052444376
